### ISSUE TITLE
Downloading Notes from comments

### ISSUE THREAD

**Issue by szuzzah** [Alec-Nelson/GobblerExchange#10]
Clicking on the note name from the comments section for that note does not try to download the note. Rather, it downloads some html regarding the website.

**Comment by mjwabby** [comment]
From a cursory look, the issue seems to be line 10 in notescomment.html. In contrast to line 62 in notes.html, it uses a variable $link that doesn't seem to be set anywhere and is probably a reserved variable. The notes.html line uses $noteslink and sets it on line 23. So i think you just need to copy over the stuff done in notes to notescomment.

**Comment by mjwabby** [comment]
Are you working on this, szuzzah (who i think is Matthew, though i can't remember for sure whose PID that is), or does someone else need to fix it before the deadline?

**Comment by mrigsbee** [comment]
This is me. I'll take a look.

**Comment by mrigsbee** [comment]
Should be fixed now (localhost), someone check it and close the issue if it's fixed for you too.

**Comment by mjwabby** [comment]
I'm getting "Failed network error" issues on local now. As in, chrome makes the little download bar with the right filename, but its not actually working.

Edit: On both the notes view and the notescomment view.

**Comment by mjwabby** [comment]
On AWS, similar issue, only now the error is "Failed - no file". Happens for both already existing files (the cat health tips on cat-lovers) and new ones (a file with the ta solutions i added to the data and algo group just now)

**Comment by mrigsbee** [comment]
I forgot. it doesn't download locally since it's not actually connected to the internet. It should work on AWS. If you didn't push your changes, then no, the files aren't in the file directory so they won't be there on AWS. Try it on AWS and it should work.

**Comment by mjwabby** [comment]
Nope, just tried readding the cat file on AWS, still gives me 'failed - no file'

**Comment by mrigsbee** [comment]
That's because your file isn't in the files system. Try uploading first.
I removed the notes that didn't exist in the file system.

**Comment by mjwabby** [comment]
I did. Unless i'm missing somethign completely? Like, i deleted the existing note, then went to add a new note, and it said i uploaded it...
![filefailed](https://cloud.githubusercontent.com/assets/8302297/24479311/a5575fb8-14ac-11e7-9820-44eda504292d.PNG)

**Comment by mjwabby** [comment]
Huh...I tried adding some other files to the data and algo group, in case there was an issue with the fact that i'd previously added that pdf (like, if the code thought it was already uploaded or something). 
When i tried adding Lecture 17's pdf, chrome showed at the bottom that it was uploading, but then when it reached 100%, the website gave me an error message saying there was a problem with the upload.
When i tried adding the TA solutions to HW 2 (in case it was a size issue, since lecture 17 is a relatively large pdf), it did the same thing as it had with the cat pdf, acting like it had uploaded, making a note, and then giving me failed no file errors when i try to download it again.

**Comment by kaityblohm** [comment]
I also got the same thing Michael did, I created a note and then tried to download it and it says Failed- No file

**Comment by mrigsbee** [comment]
Alright it should be fixed (localhost only). Also,you should be able to download via localhost. Not sure why i originally thought you couldn't but I was wrong. This will only work with notes you upload from now on so delete any old notes on your local install since they won't be able to be downloaded. Let me know if there's still issues with downloading, otherwise close the issue if it seems to work. 

LOL JK. One sec. I'll update when I fixed again

Ok it should work now. I had to account for windows and their backslashes in the file paths. Annoying. But it should work for everyone's localhost.....as long as you use windows. I have it ready to work with AWS but it'll only be active when it's in AWS.

**Comment by mrigsbee** [comment]
Ok so it should definitely work now. If you're **not** using Windows, just modify the 'notes_directory' session variable in global.php with your path to the '<yourpath>/GobblerExchange/public/notes/' folder. Otherwise, if you're already using windows, it should work. 
Again, make sure you're only testing with notes you've added after I've made the fix.

**Comment by mjwabby** [comment]
Doesn't work in the comments view, but that should just need the fix i suggested much earlier in this thread, so i'll probably fix that during the meeting today.

**Comment by mjwabby** [comment]
Fixed the comments issue; i think megan said she would fix the fact that reuploading doesn't work when she gets the chance so she can close this when she does i guess?

**Comment by mrigsbee** [comment]
Just pushed. Editing notes and updating the PDF should work now. Someone double check for me and close the issue if it also works for you too.
