### ISSUE TITLE
Error when no poll results

### ISSUE THREAD

**Issue by alexlamon** [Alec-Nelson/GobblerExchange#17]
When no one has submitted a vote for a poll, if you click "View Results" everything comes up as expected but if you want to go back by clicking "View Poll Options" the following errors pop up.

Notice: Undefined index: polloption in /Applications/XAMPP/xamppfiles/htdocs/GobblerExchange/app/controller/PollController.php on line 203

Fatal error: Call to a member function get() on null in /Applications/XAMPP/xamppfiles/htdocs/GobblerExchange/app/controller/PollController.php on line 205

**Comment by mrigsbee** [comment]
Do you mean when no one has voted on any of the options? What are you seeing?

**Comment by mrigsbee** [comment]
I'm not getting this error. Maybe try deleting all of your polls and see if it happens again? I did commit some poll-related stuff just now but I don't think it's related to the error you had. Still, pull first and see if that did anything.

**Comment by alexlamon** [comment]
I'm still getting it -- I get it for any poll that I haven't submitted my own vote for.

**Comment by mrigsbee** [comment]
Can you send a screenshot? Also, let me know the username you're logged in on.

**Comment by alexlamon** [comment]
I tried to send a video but it's too big. Basically, I was getting the error is occurring only when the user hasn't submitted their own response to the poll. So there could be other responses but if I don't vote then I get the error. I'll share the video with you on Google Drive.

**Comment by mrigsbee** [comment]
That's really strange. I can't seem to replicate it. My best guess is that maybe there's some corruption with the data in your local database. Can you go to localhost/phpmyadmin, drop all the tables in the database, and import this SQL file I've attached? It's blank so you'll have to re-register and re-create any posts and such, but it might fix the problem. I had to put the SQL file in a zip folder since GitHub won't let me attach the SQL file itself.
[gobbler_exchange_empty.zip](https://github.com/Alec-Nelson/GobblerExchange/files/911859/gobbler_exchange_empty.zip)

**Comment by mrigsbee** [comment]
@alexlamon Did clearing out the database work?

**Comment by mrigsbee** [comment]
Hey @alexlamon, I fixed this on localhost. Let me know if you still are getting the error.

**Comment by alexlamon** [comment]
It works!
