### ISSUE TITLE
Chat doesn't show up on AWS on Chrome for some users.

### ISSUE THREAD

**Issue by mjwabby** [Alec-Nelson/GobblerExchange#8]
I think Alec and Megan said right before class started that it was only new users that had this problem.

**Comment by gdcolella** [comment]
Is this happening on a local pull or on amazon?

**Comment by mjwabby** [comment]
AWS, yeah. Works on local for me.

Edit: Using user mjwabby atm.

**Comment by gdcolella** [comment]
Reproduced this, I'll take it

**Comment by gdcolella** [comment]
It looks like we don't do session negotiation in postlogin() for new users. Maybe postlogin() isn't been called or the relevant code is not triggering here.

OK, the problem occurs on your first login. I made a new user, logged in, and the chat failed. I signed out, signed back in as the same user, and the chat worked. 
My code to negotiate a chat session isn't being called in this case - bringing in Alec since he was working on the registration flow.

**Comment by mjwabby** [comment]
Yeah, the "log in when you register" is the issue. Should we just make is so they have to login after they register? Dump them back on the login page with a confirmation message?

**Comment by Alec-Nelson** [comment]
No groupId is set on registration, because a new user would not have added any new groups yet. So the groupId should be set on new group creation.

**Comment by Alec-Nelson** [comment]
Or Alternatively redirect to login screen after registration.

**Comment by gdcolella** [comment]
@Alec-Nelson 
The issue here seems to be that my code on line  95 in postlogin() of server controller is not being run in this login case. We either need to break chat negotiation into its own function that's called whenever a user session is being setup, or we need to call postlogin() in the registration case.

**Comment by Alec-Nelson** [comment]
@gdcolella 
Calling postlogin() in registration case would redirect to login with a message that doesn't make sense. So It would probably be simpler to redirect to the login after registration in every case.

**Comment by Alec-Nelson** [comment]
Changed registration auto login and made success message for registration on login page here c210d6a5dac118204df4c94b2b57359213eae2f9

**Comment by mjwabby** [comment]
Worked for me on local on chrome.
